import type { QuizQuestion } from '../quiz-questions';
export const FRAGEN: QuizQuestion[] = [
  { q: 'Welcher Planet ist der Sonne am nächsten?', options: ['Venus', 'Merkur', 'Mars', 'Erde'], correct: 1 },
  { q: 'Wie viele Kontinente gibt es?', options: ['5', '6', '7', '8'], correct: 2 },
  { q: 'Welches ist das chemische Symbol für Gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correct: 2 },
  { q: 'Welcher Fluss fließt durch Paris?', options: ['Rhein', 'Seine', 'Loire', 'Donau'], correct: 1 },
  { q: 'Wie viele Beine hat eine Spinne?', options: ['6', '8', '10', '12'], correct: 1 },
  { q: 'Welches ist das größte Land der Erde nach Fläche?', options: ['China', 'USA', 'Kanada', 'Russland'], correct: 3 },
  { q: 'Welches Tier ist das größte lebende Tier der Welt?', options: ['Elefant', 'Blauwal', 'Giraffe', 'Pottwal'], correct: 1 },
  { q: 'Wie viele Farben hat ein Regenbogen klassisch?', options: ['5', '6', '7', '8'], correct: 2 },
  { q: 'Welches Gas atmen Menschen zum Leben ein?', options: ['Stickstoff', 'Kohlendioxid', 'Sauerstoff', 'Helium'], correct: 2 },
  { q: 'In welchem Land steht die Freiheitsstatue?', options: ['Frankreich', 'USA', 'England', 'Kanada'], correct: 1 },
  { q: 'Welches ist der höchste Berg der Welt?', options: ['K2', 'Mont Blanc', 'Mount Everest', 'Kilimandscharo'], correct: 2 },
  { q: 'Wie viele Minuten hat eine Stunde?', options: ['30', '60', '90', '100'], correct: 1 },
  { q: 'Welche Farbe entsteht, wenn man Blau und Gelb mischt?', options: ['Grün', 'Orange', 'Lila', 'Braun'], correct: 0 },
  { q: 'Welcher Ozean ist der größte?', options: ['Atlantik', 'Indischer Ozean', 'Pazifik', 'Arktischer Ozean'], correct: 2 },
  { q: 'Wie viele Zähne hat ein erwachsener Mensch normalerweise?', options: ['28', '30', '32', '36'], correct: 2 },
  { q: 'Welches Organ pumpt das Blut durch den Körper?', options: ['Lunge', 'Leber', 'Herz', 'Niere'], correct: 2 },
  { q: 'In welcher Stadt steht der Eiffelturm?', options: ['London', 'Rom', 'Paris', 'Berlin'], correct: 2 },
  { q: 'Welches Metall ist bei Raumtemperatur flüssig?', options: ['Eisen', 'Quecksilber', 'Blei', 'Zinn'], correct: 1 },
  { q: 'Wie viele Saiten hat eine klassische Gitarre?', options: ['4', '5', '6', '7'], correct: 2 },
  { q: 'Welcher Kontinent ist der kälteste?', options: ['Europa', 'Asien', 'Antarktika', 'Südamerika'], correct: 2 },
  { q: 'Welches Tier wird als König der Tiere bezeichnet?', options: ['Tiger', 'Löwe', 'Bär', 'Elefant'], correct: 1 },
  { q: 'Was misst man mit einem Thermometer?', options: ['Gewicht', 'Temperatur', 'Geschwindigkeit', 'Lautstärke'], correct: 1 },
  { q: 'Welches ist die Hauptstadt von Italien?', options: ['Mailand', 'Venedig', 'Rom', 'Neapel'], correct: 2 },
  { q: 'Wie viele Planeten hat unser Sonnensystem?', options: ['7', '8', '9', '10'], correct: 1 },
  { q: 'Welches Werkzeug nutzt man, um einen Nagel einzuschlagen?', options: ['Säge', 'Hammer', 'Schraubenzieher', 'Zange'], correct: 1 },
  { q: 'Welche Sprache spricht man hauptsächlich in Brasilien?', options: ['Spanisch', 'Portugiesisch', 'Englisch', 'Französisch'], correct: 1 },
  { q: 'Aus welchem Material besteht Glas hauptsächlich?', options: ['Sand', 'Holz', 'Eisen', 'Kunststoff'], correct: 0 },
  { q: 'Wie viele Bundesländer hat Deutschland?', options: ['14', '15', '16', '17'], correct: 2 },
  { q: 'Welches Vitamin liefert vor allem die Sonne?', options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], correct: 2 },
  { q: 'Welches ist der schnellste Landtier der Welt?', options: ['Gepard', 'Löwe', 'Pferd', 'Antilope'], correct: 0 },
];
