import type { QuizQuestion } from '../quiz-questions';
export const FRAGEN: QuizQuestion[] = [
  { q: 'Welches Studio produziert die Avengers-Filme?', options: ['Marvel', 'DC', 'Pixar', 'Warner Bros'], correct: 0 },
  { q: 'Wie heisst der Zauberschueler in den Harry-Potter-Filmen?', options: ['Frodo', 'Harry Potter', 'Luke Skywalker', 'Percy Jackson'], correct: 1 },
  { q: 'In welcher Serie kaempfen Familien um den Eisernen Thron?', options: ['Vikings', 'The Witcher', 'Game of Thrones', 'Rome'], correct: 2 },
  { q: 'Welcher Schauspieler spielt Iron Man im Marvel-Universum?', options: ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo', 'Robert Downey Jr.'], correct: 3 },
  { q: 'Aus welchem Film stammt der Satz "Moege die Macht mit dir sein"?', options: ['Star Wars', 'Star Trek', 'Matrix', 'Avatar'], correct: 0 },
  { q: 'Welche Trickfilm-Firma gehoert zu Disney und machte Toy Story?', options: ['DreamWorks', 'Pixar', 'Illumination', 'Ghibli'], correct: 1 },
  { q: 'Wie heisst die Netflix-Serie mit dem Upside Down und Eleven?', options: ['Dark', 'The Crown', 'Stranger Things', 'Ozark'], correct: 2 },
  { q: 'Welcher gruene Oger ist die Hauptfigur eines DreamWorks-Films?', options: ['Hulk', 'Yoda', 'Grinch', 'Shrek'], correct: 3 },
  { q: 'In welchem Film sagt der Hauptcharakter "Ich bin der Koenig der Welt"?', options: ['Titanic', 'Gladiator', 'Braveheart', 'Pirates of the Caribbean'], correct: 0 },
  { q: 'Welcher Schauspieler ist bekannt als Jack Sparrow?', options: ['Brad Pitt', 'Johnny Depp', 'Tom Cruise', 'Orlando Bloom'], correct: 1 },
  { q: 'Welche Animationsfigur ruft oft "To infinity and beyond"?', options: ['Woody', 'Mike Wazowski', 'Buzz Lightyear', 'Olaf'], correct: 2 },
  { q: 'Welche Serie handelt von einem Chemielehrer, der Drogen kocht?', options: ['Narcos', 'The Wire', 'Dexter', 'Breaking Bad'], correct: 3 },
  { q: 'Wer ist der Erzfeind von Batman?', options: ['Joker', 'Loki', 'Thanos', 'Venom'], correct: 0 },
  { q: 'Welcher Film spielt im Traum-Universum mit verschachtelten Ebenen?', options: ['Interstellar', 'Inception', 'Tenet', 'The Matrix'], correct: 1 },
  { q: 'Wie heisst der gelbe Schwamm aus der Zeichentrickserie?', options: ['Patrick', 'Squidward', 'SpongeBob', 'Plankton'], correct: 2 },
  { q: 'Welcher Schauspieler spielt Thor im Marvel-Universum?', options: ['Chris Pratt', 'Chris Evans', 'Tom Hiddleston', 'Chris Hemsworth'], correct: 3 },
  { q: 'Aus welchem Disney-Film stammt das Lied "Let It Go"?', options: ['Die Eiskoenigin', 'Vaiana', 'Rapunzel', 'Cinderella'], correct: 0 },
  { q: 'Welche Streaming-Plattform produzierte die Serie "The Mandalorian"?', options: ['Netflix', 'Disney+', 'Amazon Prime', 'HBO'], correct: 1 },
  { q: 'Wie heisst der Hobbit, der den Einen Ring traegt?', options: ['Bilbo', 'Sam', 'Frodo', 'Gandalf'], correct: 2 },
  { q: 'Welcher Film hat den beruehmten Hai als Antagonisten?', options: ['Titanic', 'Aquaman', 'Moby Dick', 'Der weisse Hai'], correct: 3 },
  { q: 'Welche Serie spielt in einem Krankenhaus und heisst nach einer Aerztin?', options: ['Greys Anatomy', 'House', 'Scrubs', 'ER'], correct: 0 },
  { q: 'Welcher Schauspieler spielt Captain Jack in Pirates of the Caribbean?', options: ['Russell Crowe', 'Johnny Depp', 'Geoffrey Rush', 'Javier Bardem'], correct: 1 },
  { q: 'Wie heisst der Loewenkoenig-Sohn aus dem Disney-Klassiker?', options: ['Mufasa', 'Scar', 'Simba', 'Timon'], correct: 2 },
  { q: 'Welcher Bandit sagt "Hasta la vista, Baby"?', options: ['Rambo', 'John Wick', 'Robocop', 'Terminator'], correct: 3 },
  { q: 'Welches Studio steht hinter den Star-Wars-Filmen seit 2012?', options: ['Disney', 'Warner Bros', 'Universal', 'Paramount'], correct: 0 },
  { q: 'Wie heisst die Serie ueber eine Anwaltskanzlei mit Saul Goodman?', options: ['Suits', 'Better Call Saul', 'Boston Legal', 'The Good Wife'], correct: 1 },
  { q: 'Welcher Schauspieler ist das Gesicht von John Wick?', options: ['Liam Neeson', 'Jason Statham', 'Keanu Reeves', 'Matt Damon'], correct: 2 },
  { q: 'Aus welchem Film stammt "Das Leben ist wie eine Schachtel Pralinen"?', options: ['The Green Mile', 'Cast Away', 'Saving Private Ryan', 'Forrest Gump'], correct: 3 },
  { q: 'Welche Serie folgt den Familien Bridgerton im England der Regency-Zeit?', options: ['Bridgerton', 'The Crown', 'Downton Abbey', 'Outlander'], correct: 0 },
  { q: 'Welcher Antagonist will in Avengers die Haelfte des Universums ausloeschen?', options: ['Ultron', 'Thanos', 'Loki', 'Hela'], correct: 1 },
];
