import type { QuizQuestion } from '../quiz-questions';

export const FRAGEN: QuizQuestion[] = [
  { q: 'Wie viele Spieler starten klassisch in einem Battle-Royale-Match in Fortnite?', options: ['50', '75', '100', '150'], correct: 2 },
  { q: 'Welches Fahrzeug schwebt mit dem Spieler langsam zu Boden, wenn man aus dem Battle Bus springt?', options: ['Gleiter', 'Fallschirm-Auto', 'Jetpack', 'Ballon'], correct: 0 },
  { q: 'Welche Ressource sammelt man NICHT mit der Spitzhacke zum Bauen?', options: ['Holz', 'Stein', 'Metall', 'Gold'], correct: 3 },
  { q: 'Wie heisst das fliegende Fahrzeug, aus dem die Spieler zu Beginn springen?', options: ['Battle Bus', 'Sky Cab', 'Drop Ship', 'Loot Van'], correct: 0 },
  { q: 'Welche Waffenseltenheit ist in Fortnite typischerweise die hoechste Stufe?', options: ['Blau (Selten)', 'Lila (Episch)', 'Gold (Legendaer)', 'Grau (Gewoehnlich)'], correct: 2 },
  { q: 'Welche Farbe hat ein Item der Seltenheit "Gewoehnlich"?', options: ['Grau', 'Gruen', 'Blau', 'Lila'], correct: 0 },
  { q: 'Was schrumpft im Verlauf eines Matches und zwingt Spieler zusammen?', options: ['Der Sturm', 'Die Lava', 'Der Nebel', 'Die Flut'], correct: 0 },
  { q: 'Wie heisst die Waehrung, mit der man im Item-Shop Skins kauft?', options: ['Gold', 'V-Bucks', 'Coins', 'Credits'], correct: 1 },
  { q: 'Welches Heil-Item stellt langsam Schild her, wenn man es trinkt?', options: ['Med-Kit', 'Schild-Trank', 'Verband', 'Bandagen'], correct: 1 },
  { q: 'Wie viel maximalen Schild kann ein Spieler standardmaessig haben?', options: ['50', '75', '100', '150'], correct: 2 },
  { q: 'Welcher Tanz wurde durch Fortnite besonders beruehmt?', options: ['Floss', 'Moonwalk', 'Twist', 'Macarena'], correct: 0 },
  { q: 'Welches Item lasst dich nach unten gleiten, um schneller zu fallen?', options: ['Re-Deploy Gleiter', 'Jetpack', 'Grapple', 'Shockwave'], correct: 0 },
  { q: 'Welche Granate stoesst Spieler und Gegner weit weg, ohne Schaden zu machen?', options: ['Splittergranate', 'Shockwave-Granate', 'Frag-Granate', 'Rauchgranate'], correct: 1 },
  { q: 'Wie heisst der ikonische lila Skin mit Drachenmotiv aus frueheren Seasons?', options: ['Drift', 'Ragnarok', 'Raven', 'Omega'], correct: 0 },
  { q: 'Welches Tier kann man in Fortnite-Wildnis zaehmen oder jagen?', options: ['Wildschwein', 'Elefant', 'Pinguin', 'Giraffe'], correct: 0 },
  { q: 'Wie nennt man die kleine Fortnite-Spielfigur, die das Banner-Symbol ziert?', options: ['Peely', 'Jonesy', 'Banner-Boi', 'Meowscles'], correct: 1 },
  { q: 'Welcher Charakter ist eine sprechende Banane?', options: ['Peely', 'Bananito', 'Fruity', 'Splode'], correct: 0 },
  { q: 'Welcher muskuloese Kater-Charakter ist ein beliebter Fortnite-Skin?', options: ['Meowscles', 'Kit', 'Cattus', 'Whiskers'], correct: 0 },
  { q: 'Wofuer steht die Abkuerzung "BR" bei Fortnite?', options: ['Battle Royale', 'Build Rush', 'Boss Run', 'Bus Ride'], correct: 0 },
  { q: 'Welches Bauteil bietet den besten direkten Schutz vor Schuessen von vorne?', options: ['Wand', 'Boden', 'Treppe', 'Dach'], correct: 0 },
  { q: 'Welche Waffe verschiesst auf kurze Distanz die hoechste Schadensspitze?', options: ['Schrotflinte', 'Scharfschuetzengewehr', 'Pistole', 'SMG'], correct: 0 },
  { q: 'Welche Waffe eignet sich am besten fuer sehr weite Entfernungen?', options: ['Scharfschuetzengewehr', 'Schrotflinte', 'SMG', 'Pistole'], correct: 0 },
  { q: 'Was passiert, wenn man im Sturm steht?', options: ['Man verliert Lebenspunkte', 'Man wird langsamer', 'Man heilt sich', 'Nichts'], correct: 0 },
  { q: 'Wie heisst der Modus, in dem Bauen deaktiviert ist?', options: ['Zero Build', 'No Build Arena', 'Pure Combat', 'Builderless'], correct: 0 },
  { q: 'Welche Aktion fuehrt man aus, um besiegte Verbuendete wieder ins Spiel zu bringen?', options: ['Wiederbeleben', 'Respawn-Kauf am Automaten', 'Heilen', 'Markieren'], correct: 1 },
  { q: 'Wie nennt man kosmetische Items, die den Charakter aussehen lassen?', options: ['Skins', 'Mods', 'Buffs', 'Perks'], correct: 0 },
  { q: 'Welches Item heilt sowohl Lebenspunkte als auch Schild ueber Zeit?', options: ['Chug Jug / Slurp', 'Verband', 'Apfel', 'Mini-Schild'], correct: 0 },
  { q: 'Welcher Battle-Pass-Charakter war ein bekannter Marvel-Superheld in einer Season?', options: ['Deadpool', 'Mario', 'Sonic', 'Kratos'], correct: 0 },
  { q: 'Wie viele Spieler bilden ein Squad im Standard-Modus?', options: ['2', '3', '4', '6'], correct: 2 },
  { q: 'Was erhaelt man, wenn man als Letzter uebrig bleibt und das Match gewinnt?', options: ['Victory Royale', 'Game Over', 'Top Score', 'Final Win'], correct: 0 },
];
