import type { QuizQuestion } from '../quiz-questions';

export const FRAGEN: QuizQuestion[] = [
  { q: 'In welchem Spiel sammelt man bunte Bausteine und kaempft gegen Creeper?', options: ['Terraria', 'Minecraft', 'Roblox', 'Fortnite'], correct: 1 },
  { q: 'Wie heisst der Erzfeind von Super Mario?', options: ['Bowser', 'Wario', 'Donkey Kong', 'Kirby'], correct: 0 },
  { q: 'Welche Firma stellt die PlayStation her?', options: ['Microsoft', 'Nintendo', 'Sony', 'Sega'], correct: 2 },
  { q: 'Wie heisst die Heldin der Tomb-Raider-Reihe?', options: ['Samus Aran', 'Lara Croft', 'Aloy', 'Bayonetta'], correct: 1 },
  { q: 'Welches Spiel spielt in der Stadt Los Santos?', options: ['GTA V', 'Watch Dogs', 'Mafia', 'Saints Row'], correct: 0 },
  { q: 'Wie heisst die gruene Held in der Legend-of-Zelda-Reihe?', options: ['Zelda', 'Link', 'Ganon', 'Navi'], correct: 1 },
  { q: 'Welches Studio entwickelt die Reihe The Witcher?', options: ['Ubisoft', 'CD Projekt Red', 'Bethesda', 'Rockstar'], correct: 1 },
  { q: 'Welche Konsole kam zuerst auf den Markt?', options: ['Nintendo Switch', 'PlayStation 5', 'Game Boy', 'Xbox Series X'], correct: 2 },
  { q: 'Wie heisst der gelbe runde Held, der Pillen frisst und vor Geistern flieht?', options: ['Sonic', 'Pac-Man', 'Kirby', 'Q-Bert'], correct: 1 },
  { q: 'Welcher Shooter spielt im Universum von Tarkov-aehnlichen Battle-Royales und heisst Call of …?', options: ['Honor', 'Duty', 'Glory', 'War'], correct: 1 },
  { q: 'Wie heisst der blaue Igel von Sega?', options: ['Tails', 'Knuckles', 'Sonic', 'Shadow'], correct: 2 },
  { q: 'In welchem Spiel faengt man Taschenmonster und trainiert sie?', options: ['Digimon', 'Pokemon', 'Yo-kai Watch', 'Monster Hunter'], correct: 1 },
  { q: 'Welche Firma entwickelt die Halo-Reihe ursprunglich?', options: ['Bungie', 'id Software', 'Valve', 'Epic Games'], correct: 0 },
  { q: 'Was bedeutet die Abkuerzung NPC?', options: ['New Player Class', 'Non-Player Character', 'Network Play Code', 'Next Player Choice'], correct: 1 },
  { q: 'Welches Spiel popularisierte das Battle-Royale-Genre mit Bauen?', options: ['PUBG', 'Apex Legends', 'Fortnite', 'Warzone'], correct: 2 },
  { q: 'Wie heisst die Marke der tragbaren Nintendo-Konsole von 1989?', options: ['Game Gear', 'Game Boy', 'PSP', 'Lynx'], correct: 1 },
  { q: 'Welcher Klempner hat einen Bruder namens Luigi?', options: ['Wario', 'Mario', 'Toad', 'Yoshi'], correct: 1 },
  { q: 'In welchem Spiel baut man Staedte und managt Sims?', options: ['SimCity', 'Cities Skylines', 'Die Sims', 'Banished'], correct: 2 },
  { q: 'Welches Studio steckt hinter Grand Theft Auto?', options: ['Rockstar Games', 'EA', 'Activision', 'Ubisoft'], correct: 0 },
  { q: 'Wie heisst Marios treues Dinosaurier-Reittier?', options: ['Bowser', 'Yoshi', 'Toad', 'Birdo'], correct: 1 },
  { q: 'Was bedeutet FPS als Spielgenre?', options: ['Fast Paced Sim', 'First-Person Shooter', 'Final Player Score', 'Free Play Server'], correct: 1 },
  { q: 'Welche Spielreihe hat einen Protagonisten namens Master Chief?', options: ['Doom', 'Halo', 'Gears of War', 'Destiny'], correct: 1 },
  { q: 'Welche Konsole ist eine Hybrid-Konsole fuer TV und unterwegs?', options: ['Xbox Series S', 'PlayStation 5', 'Nintendo Switch', 'Steam Box'], correct: 2 },
  { q: 'Wie nennt man Spielerfiguren, die andere Spieler steuern, im Gegensatz zu NPCs?', options: ['Bots', 'Avatare', 'Mobs', 'Items'], correct: 1 },
  { q: 'In welchem Spiel ist Kratos der Hauptcharakter?', options: ['Devil May Cry', 'God of War', 'Dark Souls', 'Bayonetta'], correct: 1 },
  { q: 'Welches Studio entwickelt die Reihe Dark Souls?', options: ['Capcom', 'FromSoftware', 'Square Enix', 'Konami'], correct: 1 },
  { q: 'Was ist ein "Speedrun"?', options: ['Ein schneller Server', 'Ein Spiel so schnell wie moeglich durchspielen', 'Ein Renn-Genre', 'Eine Internetverbindung'], correct: 1 },
  { q: 'Wie heisst der Plattform-Store von Valve fuer PC-Spiele?', options: ['Epic Store', 'GOG', 'Steam', 'Origin'], correct: 2 },
  { q: 'In welcher Reihe schleicht Agent 47 als Auftragskiller?', options: ['Splinter Cell', 'Hitman', 'Dishonored', 'Assassins Creed'], correct: 1 },
  { q: 'Was bedeutet "GG" im Gaming-Chat?', options: ['Get Going', 'Good Game', 'Game Glitch', 'Go Go'], correct: 1 },
];
